remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Valencia Heat
description: Social Basketball in Valencia
show_downloads: false

logo: /assets/img/valencia-heat-logo-vector.jpg
